### ISSUE TITLE
新建工程，然后把代码放到里面，报错，新新手，请教怎么破解

### ISSUE THREAD

**Issue by 12343954** [shelwee/UpdateHelper#2]
你这个怎么用？

用libs里的jar？还是res里面的源代码？

教程写的能不能适用于新手？谢谢

**Comment by shelwee** [comment]
下载这个项目，然后导入到你的项目中。IDE导入步骤：
Eclipse：进入工程设置，添加library，选择UpdateHelper；
AS：open module settings,，Dependencies，+ ，module dependency， 选择UpdateHelper。

**Comment by 12343954** [comment]
谢谢哈，我先研究一下，不过我用的是坑爹的 Android Studio，快崩溃了，如果不行，还得上来请教您，能留个email吗？谢谢 @shelwee

**Comment by 12343954** [comment]
@shelwee  你好，现在代码加进去了，但是运行时报错，提示：

03-02 07:49:14.728 8595-8595/com.koooke.myapplication E/AndroidRuntime: FATAL EXCEPTION: main
                                                                        Process: com.koooke.myapplication, PID: 8595
                                                                        android.view.WindowManager$BadTokenException: *_Unable to add window *_-- token null is not for an application
                                                                            at android.view.ViewRootImpl.setView(ViewRootImpl.java:571)
                                                                            at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:310)
                                                                            at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:85)
                                                                            at android.app.Dialog.show(Dialog.java:319)
                                                                            at com.shelwee.update.UpdateHelper.showUpdateUI(UpdateHelper.java:206)
                                                                            at com.shelwee.update.UpdateHelper.access$1700(UpdateHelper.java:56)
                                                                            at com.shelwee.update.UpdateHelper$AsyncCheck.onPostExecute(UpdateHelper.java:299)
                                                                            at com.shelwee.update.UpdateHelper$AsyncCheck.onPostExecute(UpdateHelper.java:262)
                                                                            at android.os.AsyncTask.finish(AsyncTask.java:651)
                                                                            at android.os.AsyncTask.-wrap1(AsyncTask.java)
                                                                            at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:668)
                                                                            at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                            at android.os.Looper.loop(Looper.java:148)
                                                                            at android.app.ActivityThread.main(ActivityThread.java:5417)
                                                                            at java.lang.reflect.Method.invoke(Native Method)
                                                                            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
                                                                            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

UpdateHelper updateHelper = new UpdateHelper.Builder(this) // this 编译报错，我改成 getApplicationContext()，运行就报错了

**Comment by 12343954** [comment]
搞定了，getApplicationContext() 不能 add UI，改成 MainActivity.this 就可以了

谢谢你的代码  @shelwee
